source "https://rubygems.org"

# Reduces boot times through caching; required in config/boot.rb
# [https://github.com/Shopify/bootsnap]
gem "bootsnap", "~> 1.18.4", require: false # Installed by default

# A multithreaded, Postgres-based, ActiveJob backend
# [https://github.com/bensheldon/good_job]
gem "good_job", "~> 4.10.0"

# Makes http request to other web servers
# [https://github.com/jnunemaker/httparty]
gem "httparty", "~> 0.23.1"

# The ruby interface for PostgreSQL
# [https://github.com/ged/ruby-pg]
gem "pg", "~> 1.5.9"

# A Ruby/Rack web server built for parallelism
# [https://github.com/puma/puma]
gem "puma", "~> 6.6.0"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# [https://github.com/cyu/rack-cors]
gem "rack-cors", "~> 2.0.2"

# A web-application framework that includes everything needed to create database-backed web applications
# [https://github.com/rails/rails]
gem "rails", "~> 8.0.2"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# [https://github.com/tzinfo/tzinfo-data]
gem "tzinfo-data", "~> 2.0.6", platforms: %i[jruby windows] # Installed by default

group :development do
  # Provides a Rails generator to produce Dockerfiles and related files.
  # [https://github.com/fly-apps/dockerfile-rails]
  gem "dockerfile-rails", "~> 1.7.9"

  # Make your Rubies go faster with this command line tool highly inspired by fast-ruby
  # [https://github.com/DamirSvrtan/fasterer]
  # gem "fasterer", "~> 0.11.0"

  # An extension to RuboCop focused on Performance optimization analysis
  # [https://github.com/rubocop/rubocop-performance]
  gem "rubocop-performance", "~> 1.25.0", require: false

  # A RuboCop extension focused on enforcing Rails best practices and coding conventions
  # [https://github.com/rubocop/rubocop-rails]
  gem "rubocop-rails", "~> 2.31.0", require: false

  # An extension to RuboCop focused on RSpec-specific analysis
  # [https://github.com/rubocop/rubocop-rspec]
  gem "rubocop-rspec", "~> 3.6.0", require: false

  # A linter & formatter built on RuboCop that brings the ethos of StandardJS to Ruby
  # [https://github.com/standardrb/standard]
  gem "standard", "~> 1.49.0"
end

group :development, :test do
  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  # [https://github.com/presidentbeef/brakeman]
  gem "brakeman", "~> 7.0.2", require: false

  # Step-by-step debugging and stack navigation in Pry
  # [https://github.com/deivid-rodriguez/pry-byebug]
  gem "pry-byebug", "~> 3.11.0"
end

group :test do
  # Rails integration of factory_bot, a fixtures replacement with a straightforward definition syntax
  # [https://github.com/thoughtbot/factory_bot_rails]
  gem "factory_bot_rails", "~> 6.4.4"
  # Rails integration of rspec, a testing framework to replace Rails' minitest
  # [https://github.com/rspec/rspec-rails]
  gem "rspec-rails", "~> 7.1.1"

  # Code coverage for Ruby with a powerful configuration library and automatic merging of coverage across test suites
  # [https://github.com/simplecov-ruby/simplecov]
  gem "simplecov", "~> 0.22.0"

  # Library for stubbing and setting expectations on HTTP requests in Ruby
  # [https://github.com/bblimke/webmock]
  gem "webmock", "~> 3.25.1"
end
