name: Linter

on:
  pull_request:
    paths:
     - api/**
  push:
    branches: [master]
    paths:
     - api/**

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./api
      - name: Run Brakeman
        run: bundle exec brakeman
        working-directory: ./api
