name: RubyOnRails

on:
  pull_request:
    paths:
     - api/**
  push:
    branches: [master]
    paths:
     - api/**

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./api
      - name: Set up PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql user: test
          postgresql password: password
      - name: Build app
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test
        working-directory: ./api
        env:
          DATABASE_URL: 'postgres://test:password@localhost/application_test'
      - name: Run RSpec
        run: bundle exec rspec --order=random
        working-directory: ./api
        env:
          DATABASE_URL: 'postgres://test:password@localhost/application_test'
